sudo: false

language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: hhvm

env:
  - DB=mysql

before_script:
  - which phpunit  
  - phpunit --version
  - git clone git://github.com/YOURLS/YOURLS-unit-tests.git tests
  - git clone git://github.com/ozh/YOURLS-fr_FR.git user/languages/fr
  - cp user/languages/fr/fr_FR.* user/languages
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp tests/yourls-tests-config-travis.php user/config.php

script: phpunit --configuration ./tests/phpunit-travis.xml.dist

notifications:
  email: false
